id: I03340544
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:46:46.022813
last_modified: 2023-02-09 14:46:46.023036
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: sa
bases:
  475C:
    base_file: 475C.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
